version: "3.5"

services:
  gotenberg:
    image: thecodingmachine/gotenberg:7
    ports:
      - "3000:3000"
    command:
      - "gotenberg"
      - "--chromium-ignore-certificate-errors"

  web:
    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
